import type { Metadata } from 'next'
import localFont from 'next/font/local'
import LoginButton from '../src/components/LoginButton'
import './globals.css'
import AuthProvider from '../src/providers/AuthProvider'
import { getSession } from './api/auth'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getSession()

    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <AuthProvider session={session}>
                    <LoginButton />
                    {children}
                </AuthProvider>
            </body>
        </html>
    )
}
