-- Create databases
CREATE DATABASE $KEYCLOAK_DB;
CREATE DATABASE $API_DB;

-- Create users
CREATE USER $KEYCLOAK_USER WITH PASSWORD '$KEYCLOAK_PASSWORD';
CREATE USER $API_USER WITH PASSWORD '$API_PASSWORD';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB TO $KEYCLOAK_USER;
GRANT ALL PRIVILEGES ON DATABASE $API_DB TO $API_USER;

-- Restrict public access (for security)
REVOKE ALL ON DATABASE $KEYCLOAK_DB FROM public;
REVOKE ALL ON DATABASE $API_DB FROM public;

-- Grant writes for table altering
\c $KEYCLOAK_DB
GRANT ALL ON SCHEMA public TO $KEYCLOAK_USER;
\c $API_DB
GRANT ALL ON SCHEMA public TO $API_USER;
